### ISSUE TITLE
Regions Nav

### ISSUE THREAD

**Issue by gloriosos** [gloriosos/website#4]
I'd really like to finesse the Regions area, need to discuss...

**Comment by saetia** [comment]
explain this once more

**Comment by gloriosos** [comment]
I want the "regions" to represent more of our global items, not just Italy.

REGIONS --> clicking this word should take us to a page similar to when we
click on DEPARTMENTS, with all of the "regions" I will set up
Italy --> will take us to the fancy map we currently have
Europe --> will take us to a page like a category page which can then be
sorted by country
N. America --> same
Other (or some clever global name I can't think of yet) --> same

Concern I have is to make sure that the country/region tags wll only show
up on these pages. When I was wrangling the other tags to enable the
sortability I was looking for in categories, the tags showed up in every
category an item was in so if I had doubled an item into two categories it
would drag the tag into both of them which was weird in a few cases. I
don't want the region/countries to be in the same sort field as all those
other tags - just only on the regions pages.

And speaking of those other tags, is there a way for them to appear in ABC
order or some other order? Right now it seems they appear randomly at the
top of the category pages

On Tue, Nov 20, 2012 at 11:43 AM, Joel Glovacki notifications@github.comwrote:

> explain this once more
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gloriosos/website/issues/4#issuecomment-10564796.

## 

_Christy Librizzi_
eCommerce & Marketing Manager

http://www.gloriosos.com/
1011 E. Brady Street
Milwaukee, WI  53202
414.272.0540 _phone_
414.272.1312 _fax_
**
http://www.gloriosos.com/  http://www.pinterest.com/gloriosos
http://www.facebook.com/GloriososItalianMarket
  http://www.twitter.com/GloriososMarket
