### ISSUE TITLE
Products DB 

### ISSUE THREAD

**Issue by gloriosos** [gloriosos/website#6]
is it possible to get a ABC index at the top to go to that area of the list instead of just the huge, long, ever-lengthening list, scrolling, scrolling through?

**Comment by saetia** [comment]
like an iPhone?
![http://i.imgur.com/N0ftN.png](http://i.imgur.com/N0ftN.png)

**Comment by gloriosos** [comment]
yes, but across the top and the bottom perhaps?

On Tue, Nov 20, 2012 at 11:06 AM, Joel Glovacki notifications@github.comwrote:

> like an iPhone?
> [image: http://i.imgur.com/N0ftN.png]https://a248.e.akamai.net/camo.github.com/cbfd4a6c40f4524224684e7c0bd1b1678821d25c/687474703a2f2f692e696d6775722e636f6d2f4e3066744e2e706e67
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gloriosos/website/issues/6#issuecomment-10563098.

## 

_Christy Librizzi_
eCommerce & Marketing Manager

http://www.gloriosos.com/
1011 E. Brady Street
Milwaukee, WI  53202
414.272.0540 _phone_
414.272.1312 _fax_
**
http://www.gloriosos.com/  http://www.pinterest.com/gloriosos
http://www.facebook.com/GloriososItalianMarket
  http://www.twitter.com/GloriososMarket

**Comment by saetia** [comment]
this is up now
