### ISSUE TITLE
online gift cert

### ISSUE THREAD

**Issue by gloriosos** [gloriosos/website#7]
We also had wanted the option to be able to sell a digital gift card, that could be redeemed online as our physical cards cannot - is this functionality set up somewhere or does it still need to be?

**Comment by saetia** [comment]
this isn't setup now. it could be done manually with what you have available to you now.
but that would get irritating very quickly. This is something I can work on. How do you handle multiple uses for in-store gift certificates?

**Comment by gloriosos** [comment]
How do you handle multiple uses for in-store gift certificates?
In-store we use gift cards which are re-loadable and automatically deduct
amount of purchase and tracks it through the merchant terminal, but
apparently they are of a sort that will not work in conjunction with the
merchant service we use with the web site. We sometimes also use paper
certificates and those we just issue a new one for the balance if they
haven't used it all up.
C

On Tue, Nov 20, 2012 at 11:01 AM, Joel Glovacki notifications@github.comwrote:

> this isn't setup now. it could be done manually with what you have
> available to you now.
> but that would get irritating very quickly. This is something I can work
> on. How do you handle multiple uses for in-store gift certificates?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gloriosos/website/issues/7#issuecomment-10562833.

## 

_Christy Librizzi_
eCommerce & Marketing Manager

http://www.gloriosos.com/
1011 E. Brady Street
Milwaukee, WI  53202
414.272.0540 _phone_
414.272.1312 _fax_
**
http://www.gloriosos.com/  http://www.pinterest.com/gloriosos
http://www.facebook.com/GloriososItalianMarket
  http://www.twitter.com/GloriososMarket
