### ISSUE TITLE
gloriosositalianmarket.com

### ISSUE THREAD

**Issue by gloriosos** [gloriosos/website#8]
this is still not forwarding

**Comment by saetia** [comment]
ugh. you must have www. set as well.
i hate www. with all of my heart

http://gloriosositalianmarket.com is not the same as
http://www.gloriosositalianmarket.com

**Comment by saetia** [comment]
should be updated in an hour:
fixes #8

**Comment by gloriosos** [comment]
the non-www gives a 404 error for me, and the www just goes to the old yuck
:)

On Wed, Nov 21, 2012 at 10:38 AM, Joel Glovacki notifications@github.comwrote:

> ugh. you must have www. set as well.
> i hate www. with all of my heart
> 
> http://gloriosositalianmarket.com is not the same as
> http://www.gloriosositalianmarket.com
> 
> On Nov 21, 2012, at 9:30 AM, gloriosos notifications@github.com wrote:
> 
> > this is still not forwarding
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/gloriosos/website/issues/8#issuecomment-10604312.

## 

_Christy Librizzi_
eCommerce & Marketing Manager

http://www.gloriosos.com/
1011 E. Brady Street
Milwaukee, WI  53202
414.272.0540 _phone_
414.272.1312 _fax_
**
http://www.gloriosos.com/  http://www.pinterest.com/gloriosos
http://www.facebook.com/GloriososItalianMarket
  http://www.twitter.com/GloriososMarket
